import { IconType } from "react-icons";

import {
  HiMiniMinus,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiMiniPlus,
  HiMiniXMark,
  HiEyeDropper,
  HiOutlineClipboard,
  HiOutlineMagnifyingGlass,
  HiCalendar,
  HiOutlineLink,
  HiArrowUpRight,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineBars3BottomLeft,
  HiOutlineHome,
  HiOutlineComputerDesktop,
  HiOutlineAcademicCap,
  HiOutlineInformationCircle,
  HiOutlineQuestionMarkCircle,
  HiOutlineQueueList,
  HiOutlineRocketLaunch,
  HiOutlineIdentification,
  HiOutlinePhoto,
  HiOutlineMap,
  HiOutlineClock,
  HiOutlineLightBulb,
  HiOutlineAdjustmentsHorizontal,
  HiOutlinePaintBrush,
  HiOutlineDocumentDuplicate,
  HiOutlineDocumentText,
  HiOutlineSquare3Stack3D,
  HiOutlineLanguage,
  HiOutlineCheckCircle,
  HiOutlineCube,
  HiOutlineBars3,
  HiOutlineExclamationTriangle,
  HiOutlineExclamationCircle,
  HiOutlineKey,
  HiOutlineShoppingCart,
  HiOutlineBell,
  HiOutlineChatBubbleLeftRight,
  HiOutlineHeart,
  HiOutlinePlay,
  HiOutlinePause,
  HiOutlinePencil,
  HiOutlineTrash,
  HiOutlineArrowRightOnRectangle,
  HiOutlineCog6Tooth,
  HiOutlineCheck,
  HiOutlineEnvelope,
  HiOutlineDocumentChartBar,
  HiOutlineSquares2X2,
  HiOutlineUser,
  HiOutlineCodeBracket,
  HiOutlineChartBar,
  HiOutlinePresentationChartLine,
  HiOutlineChartPie,
  HiOutlineArrowTrendingUp,
  HiOutlineCpuChip,
} from "react-icons/hi2";

import { LiaCubesSolid } from "react-icons/lia";

import { RiDiscountPercentLine, RiVisaLine } from "react-icons/ri";
import { PiRuler, PiToggleLeft, PiTShirt } from "react-icons/pi";
import { FaDiscord, FaGithub, FaGoogle, FaLinkedin, FaMailchimp, FaThreads } from "react-icons/fa6";
import { LuChevronsLeftRight } from "react-icons/lu";

export const iconLibrary: Record<string, IconType> = {
  chevronsLeftRight: LuChevronsLeftRight,
  email: HiOutlineEnvelope,
  computer: HiOutlineComputerDesktop,
  help: HiOutlineQuestionMarkCircle,
  info: HiOutlineInformationCircle,
  warning: HiOutlineExclamationTriangle,
  danger: HiOutlineExclamationCircle,
  checkbox: HiOutlineCheck,
  check: HiOutlineCheckCircle,
  play: HiOutlinePlay,
  pause: HiOutlinePause,
  eyeDropper: HiEyeDropper,
  code: HiOutlineCodeBracket,
  clipboard: HiOutlineClipboard,
  person: HiOutlineUser,
  settings: HiOutlineCog6Tooth,
  logout: HiOutlineArrowRightOnRectangle,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  discord: FaDiscord,
  google: FaGoogle,
  github: FaGithub,
  apps: HiOutlineSquares2X2,
  arrowUpRight: HiArrowUpRight,
  minus: HiMiniMinus,
  plus: HiMiniPlus,
  calendar: HiCalendar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  search: HiOutlineMagnifyingGlass,
  notification: HiOutlineBell,
  visa: RiVisaLine,
  security: HiOutlineShieldCheck,
  sparkle: HiOutlineSparkles,
  document: HiOutlineBars3BottomLeft,
  linkedin: FaLinkedin,
  analytics: HiOutlineDocumentChartBar,
  threads: FaThreads,
  home: HiOutlineHome,
  scholar: HiOutlineAcademicCap,
  queue: HiOutlineQueueList,
  rocket: HiOutlineRocketLaunch,
  card: HiOutlineIdentification,
  image: HiOutlinePhoto,
  roadmap: HiOutlineMap,
  changelog: HiOutlineClock,
  lightbulb: HiOutlineLightBulb,
  config: HiOutlineAdjustmentsHorizontal,
  mailchimp: FaMailchimp,
  style: HiOutlinePaintBrush,
  pages: HiOutlineDocumentDuplicate,
  learn: HiOutlineAcademicCap,
  page: HiOutlineDocumentText,
  chat: HiOutlineChatBubbleLeftRight,
  like: HiOutlineHeart,
  project: HiOutlineSquare3Stack3D,
  article: HiOutlineQueueList,
  language: HiOutlineLanguage,
  components: HiOutlineCube,
  sidebar: HiOutlineBars3,
  password: HiOutlineKey,
  tshirt: PiTShirt,
  cart: HiOutlineShoppingCart,
  ruler: PiRuler,
  discount: RiDiscountPercentLine,
  edit: HiOutlinePencil,
  copy: HiOutlineDocumentDuplicate,
  delete: HiOutlineTrash,
  switch: PiToggleLeft,
  modules: LiaCubesSolid,
  barChart: HiOutlineChartBar,
  lineChart: HiOutlineArrowTrendingUp,
  pieChart: HiOutlineChartPie,
  lineBarChart: HiOutlinePresentationChartLine,
  chip: HiOutlineCpuChip
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;