import { IconType } from "react-icons";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiOutlineArrowPath,
  HiOutlineSun,
  HiOutlineMoon,
  HiMiniMinus,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiMiniPlus,
  HiMiniUser,
  HiMiniXMark,
  HiEyeDropper,
  HiOutlineClipboard,
  HiOutlineMagnifyingGlass,
  HiCalendar,
  HiOutlineLink,
  HiArrowUpRight,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineBars3BottomLeft,
  HiOutlineHome,
  HiOutlineComputerDesktop,
  HiOutlineAcademicCap,
  HiOutlineInformationCircle,
  HiOutlineQuestionMarkCircle,
  HiOutlineQueueList,
  HiOutlineRocketLaunch,
  HiOutlineIdentification,
  HiOutlinePhoto,
  HiOutlineMap,
  HiOutlineClock,
  HiOutlineLightBulb,
  HiOutlineAdjustmentsHorizontal,
  HiOutlinePaintBrush,
  HiOutlineDocumentDuplicate,
  HiOutlineDocumentText,
  HiOutlineSquare3Stack3D,
  HiOutlineLanguage,
  HiOutlineCheckCircle,
  HiOutlineCube,
  HiOutlineBars3,
  HiOutlineExclamationTriangle,
  HiOutlineExclamationCircle,
  HiOutlineKey,
  HiOutlineShoppingCart,
  HiOutlineBell,
  HiOutlineChatBubbleLeftRight,
  HiOutlineHeart,
} from "react-icons/hi2";

import { RiDiscountPercentLine, RiVisaLine } from "react-icons/ri";
import { PiRuler, PiTShirt } from "react-icons/pi";
import { FaDiscord, FaGithub, FaGoogle, FaLinkedin, FaMailchimp, FaThreads } from "react-icons/fa6";
import { LuChevronsLeftRight } from "react-icons/lu";

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  chevronsLeftRight: LuChevronsLeftRight,
  refresh: HiOutlineArrowPath,
  light: HiOutlineSun,
  dark: HiOutlineMoon,
  computer: HiOutlineComputerDesktop,
  help: HiOutlineQuestionMarkCircle,
  info: HiOutlineInformationCircle,
  warning: HiOutlineExclamationTriangle,
  danger: HiOutlineExclamationCircle,
  check: HiOutlineCheckCircle,
  eyeDropper: HiEyeDropper,
  clipboard: HiOutlineClipboard,
  person: HiMiniUser,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  discord: FaDiscord,
  google: FaGoogle,
  github: FaGithub,
  arrowUpRight: HiArrowUpRight,
  minus: HiMiniMinus,
  plus: HiMiniPlus,
  calendar: HiCalendar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  search: HiOutlineMagnifyingGlass,
  notification: HiOutlineBell,
  visa: RiVisaLine,
  security: HiOutlineShieldCheck,
  sparkle: HiOutlineSparkles,
  document: HiOutlineBars3BottomLeft,
  linkedin: FaLinkedin,
  threads: FaThreads,
  home: HiOutlineHome,
  scholar: HiOutlineAcademicCap,
  queue: HiOutlineQueueList,
  rocket: HiOutlineRocketLaunch,
  card: HiOutlineIdentification,
  image: HiOutlinePhoto,
  roadmap: HiOutlineMap,
  changelog: HiOutlineClock,
  lightbulb: HiOutlineLightBulb,
  config: HiOutlineAdjustmentsHorizontal,
  mailchimp: FaMailchimp,
  style: HiOutlinePaintBrush,
  pages: HiOutlineDocumentDuplicate,
  learn: HiOutlineAcademicCap,
  page: HiOutlineDocumentText,
  chat: HiOutlineChatBubbleLeftRight,
  like: HiOutlineHeart,
  project: HiOutlineSquare3Stack3D,
  article: HiOutlineQueueList,
  language: HiOutlineLanguage,
  components: HiOutlineCube,
  sidebar: HiOutlineBars3,
  password: HiOutlineKey,
  tshirt: PiTShirt,
  cart: HiOutlineShoppingCart,
  ruler: PiRuler,
  discount: RiDiscountPercentLine
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;